optimize condenseTree and computeBoundingBox
dhconnelly/rtreego pull request #44
Opened 2022-08-18 02:36 UTC by fumin

condenseTree contains memory allocations that when triggered causes the
following time spent:

runtime.mheap.alloc 39.27%

![before_mheap](https://user-images.githubusercontent.com/765222/185280374-11c6b9e5-dab4-49c8-8424-ae54327ce1b9.svg)

Similarly, particular Delete heavy workloads might trigger unnecessary

computeBoundingBox 16.57%

![before_computeBoundingBox](https://user-images.githubusercontent.com/765222/185280403-58dd7394-11b4-4ff2-8e09-330ba8f21e61.svg)

This change fixes these performance issues.

![after](https://user-images.githubusercontent.com/765222/185280420-fb271840-aa42-4b16-a2d6-1b9e604a24c4.svg)

2022-08-18 17:36 UTC, dhconnelly requested changes

2022-08-18 17:36 UTC, dhconnelly commented on rtree.go
> +	tree.deleted = tree.deleted[:0]
```suggestion
	// reset the deleted buffer
	tree.deleted = tree.deleted[:0]
```

2022-08-18 17:36 UTC, dhconnelly commented on rtree.go
> +			idx := -1
```suggestion
			// find n and delete it by swapping the last entry into its place
			idx := -1
```

2022-08-18 17:37 UTC, dhconnelly commented
looks good, just adding a couple of small comments would be helpful!

2022-08-19 00:47 UTC, fumin commented
> looks good, just adding a couple of small comments would be helpful!

Applied the suggestions therein, thanks for the review.

2022-08-19 00:54 UTC, dhconnelly approved these changes

2022-08-19 00:54 UTC, merged